### PR TITLE
Remove default owner

### LINKED ISSUE #228: Remove default owner
It's been suggested we don't default the `owner` setting, instead forcing the user to set it in the config, like we do with `username` and `password`

### PR DESCRIPTION
**Pull request by RaceProUK**
Fixes #228

### CODE REVIEW

**Comment by RaceProUK** [comment]
Ah poo... that last commit wasn't meant to go in this PR :blush:

**Comment by AccaliaDeElementia** [comment]
want to back the change out or run with it?

we can remove it from the PR if you like.

**Comment by RaceProUK** [comment]
Eh, may as well run with it; it either goes in this PR or the next, so it's going in one way or another :smile:
Assuming of course the change is desirable

**Comment by AccaliaDeElementia** [comment]
i'll take it then!

**Pull request merged**
