### PR TITLE
Docs update

### PR DESCRIPTION
**Pull request by yamikuronue**
Docs for providers

### CODE REVIEW

**Comment by AccaliaDeElementia** [comment]
hmm.... one note that i observe on the docs.... the existence of the bindX functions is naught but an implementation detail. there are other patterns that would produce the same effects as the bindX closure functionality does.

we should probably omit those functions and instead document the effect the bindX solution has on the way a forum instance behaves instead.

also i really need to get a moment to wrap my head around your DI suggestion, because it's a real brain buster right now.

**Comment by yamikuronue** [comment]
You know, that's fair. The closure bit only exists between the Forum and the whatevers.

**Comment by AccaliaDeElementia** [comment]
Is this still in progress?

Or shall we merge now?

**Comment by yamikuronue** [comment]
Are you happy with the current state? Or do you want to wait until I get a chance to remove the closure info?

**Comment by AccaliaDeElementia** [comment]
I'd prefer the closure info to be removed before we ship the initial docs, but if that's going to be a significant delay because real life suxxors then we can look into merging now and issuing an update later.

**Comment by AccaliaDeElementia** [comment]
:shipit:

**Pull request merged**
