### PR TITLE
test(sinon-chai)

### PR DESCRIPTION
**Pull request by errorx666**
Converted some more tests to using sinon-chai (reads nicer and also gives more informative error message).  Also added a new constraint that spies are `calledWith().once` or `calledOnce` (so it fails if they are called 2+ times as well as if they are not called).

### CODE REVIEW

**Comment by AccaliaDeElementia** [comment]
Test updates look good.

Assuming appveyor completes clean i'd say you're good to merge.

theoretically you have merge permission on the repo now. so.... if you don't i'm confused.

**Comment by errorx666** [comment]
@AccaliaDeElementia That's a negative:
image

**Comment by AccaliaDeElementia** [comment]
huh.... okay i need to do more reading on how these darned permissions work...

in the mean time, merging.

**Comment by errorx666** [comment]
I just noticed some redundancies with calledOnce and callCount.equals(1).  Harmless, though.

**Comment by errorx666** [comment]
Better to check the same thing twice than not at all.

**Pull request merged**
